name: Sync Fork

on:
  schedule:
    - cron: '0 5 * * *' # every day
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: crazypeace
          base: master
          head: master
